### PR TITLE
add soft scoring example,scan def and update readme

### PR DESCRIPTION
**Pull request by akumar-cs**
[#issue-2829](https://github.com/CognitiveScale/certifai/issues/2829)

### CODE REVIEW

**Review by cdraper-CS — APPROVED** [review]
LGTM but please also update model/README.md to highlight this example shows wrapping a model with soft scoring.

**Comment by cdraper-CS** [comment]
@akumar-cs  I noticed when running the gunicorned model server that it creates a pkl file in current folder.  Is this going to cause issues if we need to get a gunicorned server running in UBI8/RHOS, given processes can only write to /tmp?

**Review by laguirre-cs — APPROVED** [review]
LGTM

**Comment by akumar-cs** [comment]
> @akumar-cs I noticed when running the gunicorned model server that it creates a pkl file in current folder. Is this going to cause issues if we need to get a gunicorned server running in UBI8/RHOS, given processes can only write to /tmp?

yes, it will. We can only write to /tmp in rhos images. Since model sdk wasn't being run in container it wasn't an issue but ill see if i can save the state to /tmp might/not be possible due to references of class paths

**Comment by akumar-cs** [comment]
> LGTM but please also update model/README.md to highlight this example shows wrapping a model with soft scoring.

Added `soft-scoring` part to  german_credit section of `models/README.md`.  Details for usage are inside the german_credit/README.md

**Pull request merged**
