### PR TITLE
example gunicorn mojo model sdk usage

### PR DESCRIPTION
**Pull request by akumar-cs**
to go with https://github.com/CognitiveScale/certifai/pull/2899

### CODE REVIEW

**Review by cdraper-CS — APPROVED** [review]
LGTM but is there some text you can add (in example or readme) to help explain that functions like __get_columns need to be on the class and not global?

**Comment by cdraper-CS** [comment]
I tried to run the example but got:
```
2020-10-27 12:37:15,072 certifai.model.sdk.simple_wrapper ERROR    No module named 'datatable'
Traceback (most recent call last):
  File "/Users/cdraper/projects/certifai/certifai_model_sdk/certifai/model/sdk/simple_wrapper.py", line 304, in _create_app
    state._run_user_func(state._ext_func_list)
  File "/Users/cdraper/projects/certifai/certifai_model_sdk/certifai/model/sdk/simple_wrapper.py", line 191, in _run_user_func
    getattr(self, f)()
  File "app_h2o_mojo_pipeline.py", line 52, in set_global_imports
    import datatable as dt
ModuleNotFoundError: No module named 'datatable'
Failed to find application object: "_create_app('.state_8551')"
[2020-10-27 12:37:15,172] WARNING in simple_wrapper: app killed
```

I have pip installed datatable, so I'm not sure what's wrong.

**Comment by cdraper-CS** [comment]
Please can you actually make the gunicorn example into a separate file and make the PR into prerelease not master? We won't be able to merge this to master until 1.3.6 is out and I'd also rather not overwrite the flask example we've already given them.

**Comment by cdraper-CS** [comment]
assume this PR is superseded by other gunicorn one into prerelease?

**Comment by akumar-cs** [comment]
> assume this PR is superseded by other gunicorn one into prerelease?

yes. closing this

**Pull request closed without merging**
