### PR TITLE
Use construct_shap_dataframe, construct_explanations_dataframe in examples

### PR DESCRIPTION
**Pull request by cdraper-CS**
Use CatEncoder, cleanup license url and test_use_case.

In Shap notebook: Used `construct_shap_dataframe` to summarize the shap values for the models displayed at the end. Looked at using the data frame in the visualizations, but it didn't really make sense.

In AnalyzeFeatureUsage and patient readmission: Used `construct_explanations_dataframe`

Note this is merge to prerelease, as its using 1.3.6 API

### CODE REVIEW

**Review by sdraper-CS — APPROVED** [review]
LGTM

**Review by akumar-cs — APPROVED** [review]

**Review by sdraper-CS — CHANGES_REQUESTED** [review]
Magic number '6' in `model_explanations` to strip the metadata.  Should make an API funcion to strip out the metadata or something

**Comment by cdraper-CS** [comment]
@sdraper-CS    Fixed the 'magic number' by adding counterfactual_feature_frequency to explanation utils (#2887). I'll rerun notebook once that is merged just to sanity check.

**Comment by cdraper-CS** [comment]
@sdraper-CS Ready for a sanity check review on this. Changes since you reviewed were to use 'counterfactual_feature_frequency' in counterfactual_feature_frequency Usage and 'counterfactual_changes' in that and patient readmission. Also to fix a misleading variable name.

**Review by sdraper-CS — APPROVED** [review]
LGTM

**Pull request merged**
