### PR TITLE
Fast explain example

### PR DESCRIPTION
**Pull request by sdraper-CS**
See issue #2971 in the Certifai repo

### CODE REVIEW

**Comment by cdraper-CS** [comment]
I updated pre-release to be equal with master in the hope that this would remove the 26 spurious commits, but it didnt. You may need to rebase.

**Comment by cdraper-CS** [comment]
Please add to model README

**Comment by cdraper-CS** [comment]
If this is intended to merge at some point, it'll need some words :-)

Need to tell user that it has category_encoders as a prereq (pip install)

**Comment by cdraper-CS** [comment]
"one-tim" compute.  Where's bert and harry?

**Comment by cdraper-CS** [comment]
The notebook runs fine for me

**Review by laguirre-cs — COMMENTED** [review]
I'm only commenting on the fast explanations notebook:

* Think Christine already found all the misspellings
* The `_wrap_sklearn_classifier` seems a little redundant (also the `CertifaiPredictorWrapper` was already imported in cell 1)
* The notebook looks fine to me, and I could re-run it problem
* (This is really a side comment) I noticed this line in the notebook: `pd.set_option('display.max_columns', None)`. I think we should be setting this value in notebooks whenever we display explanations. I know there are a couple examples that have truncated tables (e.g. regression notebook)

**Comment by sdraper-CS** [comment]
@cdraper-CS @laguirre-cs Addressed all review comments I think

**Review by laguirre-cs — APPROVED** [review]
(Again only looking at the notebook and related README entry)

Needs a small update for the README entry, but notebook looks good. I think a markdown cell comparing speed up would pack a good punch at the end (but I'm assuming it's still too early to try and do that comparison). So, i'm approving w/ the caveat of the README update.

**Review by cdraper-CS — COMMENTED** [review]
I checked this runs without needing the beta flag, so I suggest you merge to master but please add a "Requires Certifai version 1.3.7+" prereq.

Found two more typos: exaplantions, neccessary

**Comment by sdraper-CS** [comment]
@cdraper-CS Addressed your final outstanding comment

**Review by cdraper-CS — APPROVED** [review]

**Pull request merged**
