### PR TITLE
R model template v1

### PR DESCRIPTION
**Pull request by akumar-cs**
r-model template work.
also cleaned up example in r-model to align with template schema

### CODE REVIEW

**Comment by akumar-cs** [comment]
@bjesudasan-CS  to test this end-end:

- run the `cortex-certifai-examples/models/r-models/train_german_credit.R` to generate the `german_credit_rf.rds` file
- use the .rds file and follow instructions in `models/containerized_models/README.md` R Model Template section

**Comment by cdraper-CS** [comment]
I pushed a commit so the index in the readme now has links so you can jump to the right section.

I tested this with the german credit example in r-models - worked fine.

**Review by cdraper-CS — APPROVED** [review]

**Comment by bjesudasan-CS** [comment]
@akumar-cs  and I have spent some time verifying this PR in my machine, was getting the below error continuously. We have also tried changing the r-cran mirror, didn't help us. will try again sometime later today or tomorrow.

```
bjesudasan@CSI-0055 ~/B/R/C/c/m/containerized_model (r_model_template_v1)> sh generated-container-model/container_util.sh build                                                                                                        (base)
Sending build context to Docker daemon  328.7kB
Step 1/13 : FROM rocker/r-apt:bionic
 ---> 6df37aecb465
Step 2/13 : RUN ls -a
 ---> Using cache
 ---> 233752b0734e
Step 3/13 : WORKDIR /
 ---> Using cache
 ---> 5365a1306c25
Step 4/13 : RUN apt-get update &&   apt-get install -y libxml2-dev
 ---> Using cache
 ---> 86a201362c22
Step 5/13 : COPY ./requirements_bin_R.txt /tmp/
 ---> Using cache
 ---> 609a0b5d2ce0
Step 6/13 : COPY ./requirements_src_R.txt /tmp/
 ---> Using cache
 ---> e39a3c7cd982
Step 7/13 : RUN cat /tmp/requirements_bin_R.txt | xargs apt-get install -y -qq
 ---> Running in c50544a640c6
E: Failed to fetch http://ppa.launchpad.net/marutter/c2d4u3.5/ubuntu/pool/main/c/callr/r-cran-callr_3.5.1-1cran1.1804.0_all.deb  Connection failed [IP: 91.189.95.85 80]
E: Failed to fetch http://ppa.launchpad.net/marutter/c2d4u3.5/ubuntu/pool/main/g/gtable/r-cran-gtable_0.3.0-1cran1ppabionic0_all.deb  Connection failed [IP: 91.189.95.85 80]
E: Failed to fetch http://ppa.launchpad.net/marutter/c2d4u3.5/ubuntu/pool/main/l/labeling/r-cran-labeling_0.4.2-1cran1.1804.0_all.deb  Connection failed [IP: 91.189.95.85 80]
E: Failed to fetch http://ppa.launchpad.net/marutter/c2d4u3.5/ubuntu/pool/main/d/data.table/r-cran-data.table_1.13.6-1cran1.1804.0_amd64.deb  Connection failed [IP: 91.189.95.85 80]
E: Failed to fetch http://ppa.launchpad.net/marutter/c2d4u3.5/ubuntu/pool/main/s/squarem/r-cran-squarem_2021.1-1cran1.1804.0_all.deb  Connection failed [IP: 91.189.95.85 80]
E: Failed to fetch http://ppa.launchpad.net/marutter/c2d4u3.5/ubuntu/pool/main/p/prodlim/r-cran-prodlim_2019.11.13-1cran1ppabionic0_amd64.deb  Connection failed [IP: 91.189.95.85 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The command '/bin/sh -c cat /tmp/requirements_bin_R.txt | xargs apt-get install -y -qq' returned a non-zero code: 123
```

**Comment by bjesudasan-CS** [comment]
Able to follow the instructions and run the r-model template successfully.

**Review by bjesudasan-CS — APPROVED** [review]

**Pull request merged**
