### PR TITLE
Gunicorn mojo support example

### PR DESCRIPTION
**Pull request by akumar-cs**
- reverted the old `app_h2_mojo_pipeline.py` file 
- added the new file as  `app_h2_mojo_pipeline_gunicorn.py`
- added docstrings to indicate user defined methods must be declared inside the wrapper class instantiating `SimpleModelWrapper`
- new pr since now we'll be merging this this to pre-release

### CODE REVIEW

**Comment by cdraper-CS** [comment]
You have a bunch of unexpected changes to clean start, xgboost etc in this PR

**Review by cdraper-CS — APPROVED** [review]
lgtm

**Review by cdraper-CS — CHANGES_REQUESTED** [review]
Remove unintended changes to xgboost, clean start, scan from definition

**Comment by akumar-cs** [comment]
> Remove unintended changes to xgboost, clean start, scan from definition

fixed

**Review by cdraper-CS — APPROVED** [review]

**Review by mchutani-CS — APPROVED** [review]

**Pull request merged**
